# Generated by Django 4.2.2 on 2024-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_task_todolist_usertodolist_delete_todo_task_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
