# Generated by Django 4.2.2 on 2024-05-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_rename_updated_at_task_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
