# Generated by Django 5.0.6 on 2024-06-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_alter_task_completed_at_alter_todolist_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='todolist',
            new_name='tasklist',
        ),
        migrations.RenameModel(
            old_name='TodoList',
            new_name='TaskList',
        ),
        migrations.CreateModel(
            name='UserTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Creator', 'Creator'), ('Viewer', 'Viewer'), ('Editor', 'Editor')], default='Creator', max_length=10)),
                ('tasklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_api.tasklist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserTodoList',
        ),
    ]
