# Generated by Django 5.0.6 on 2024-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0006_itemposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertasklist',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemPosition',
        ),
    ]
